-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 21:25:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_user` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `verified` TINYINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organizer` (
  `id_organizer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `id_creator` INT NOT NULL,
  PRIMARY KEY (`id_organizer`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_organizer_user1_idx` (`id_creator` ASC) VISIBLE,
  CONSTRAINT `fk_organizer_user1`
    FOREIGN KEY (`id_creator`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `id_event` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `id_creator` VARCHAR(45) NULL,
  `id_organizer` INT NOT NULL,
  `eventscol` VARCHAR(45) NULL,
  `date` DATETIME NOT NULL,
  `ubication` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_event`),
  INDEX `fk_events_organizer1_idx` (`id_organizer` ASC) VISIBLE,
  CONSTRAINT `fk_events_organizer1`
    FOREIGN KEY (`id_organizer`)
    REFERENCES `mydb`.`organizer` (`id_organizer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interests` (
  `id_interest` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_interest`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organizer_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organizer_admins` (
  `id_organizer_admins` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_organizer` INT NOT NULL,
  PRIMARY KEY (`id_organizer_admins`),
  INDEX `fk_organizer_admins_user1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_organizer_admins_organizer1_idx` (`id_organizer` ASC) VISIBLE,
  CONSTRAINT `fk_organizer_admins_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizer_admins_organizer1`
    FOREIGN KEY (`id_organizer`)
    REFERENCES `mydb`.`organizer` (`id_organizer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events_interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`events_interests` (
  `id_event_interest` INT NOT NULL,
  `id_event` INT NOT NULL,
  `id_interest` INT NOT NULL,
  PRIMARY KEY (`id_event_interest`),
  INDEX `fk_events_interests_events1_idx` (`id_event` ASC) VISIBLE,
  INDEX `fk_events_interests_interests1_idx` (`id_interest` ASC) VISIBLE,
  CONSTRAINT `fk_events_interests_events1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`events` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_interests_interests1`
    FOREIGN KEY (`id_interest`)
    REFERENCES `mydb`.`interests` (`id_interest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_interests` (
  `id_user_interest` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_interest` INT NOT NULL,
  PRIMARY KEY (`id_user_interest`),
  INDEX `fk_users_interests_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_users_interests_interests1_idx` (`id_interest` ASC) VISIBLE,
  CONSTRAINT `fk_users_interests_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_interests_interests1`
    FOREIGN KEY (`id_interest`)
    REFERENCES `mydb`.`interests` (`id_interest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organizer_followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organizer_followers` (
  `id_organizer_followers` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_organizer` INT NOT NULL,
  PRIMARY KEY (`id_organizer_followers`),
  INDEX `fk_organizer_followers_users1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_organizer_followers_organizer1_idx` (`id_organizer` ASC) VISIBLE,
  CONSTRAINT `fk_organizer_followers_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizer_followers_organizer1`
    FOREIGN KEY (`id_organizer`)
    REFERENCES `mydb`.`organizer` (`id_organizer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saved_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saved_events` (
  `id_saved_events` INT NOT NULL AUTO_INCREMENT,
  `id_events` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_saved_events`),
  INDEX `fk_saved_events_events1_idx` (`id_events` ASC) VISIBLE,
  INDEX `fk_saved_events_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_saved_events_events1`
    FOREIGN KEY (`id_events`)
    REFERENCES `mydb`.`events` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saved_events_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tickets` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `id_event` INT NOT NULL,
  `id_user` INT NOT NULL,
  `state` INT NOT NULL,
  `buy_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `fk_tickets_events1_idx` (`id_event` ASC) VISIBLE,
  INDEX `fk_tickets_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_events1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`events` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_type` (
  `id_post_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_post_type`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `id_post_type` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `id_event` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_posts_post_type1_idx` (`id_post_type` ASC) VISIBLE,
  INDEX `fk_posts_events1_idx` (`id_event` ASC) VISIBLE,
  INDEX `fk_posts_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_posts_post_type1`
    FOREIGN KEY (`id_post_type`)
    REFERENCES `mydb`.`post_type` (`id_post_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_events1`
    FOREIGN KEY (`id_event`)
    REFERENCES `mydb`.`events` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  `id_post` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comments_posts1_idx` (`id_post` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`id_post`)
    REFERENCES `mydb`.`posts` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
